### ISSUE TITLE
'Cannot reach server' Error message

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#118]
The viewer webpage shows an Server Connection Error when accessing the webpage - however this message disappears when refreshing the webpage and everything is fine afterwards. 

![image](https://user-images.githubusercontent.com/23457217/73340023-37eddc00-427a-11ea-9c92-d238618f67aa.png)

This error message is misleading and might scare away users.

**Comment by forman** [comment]
This message is displayed only, if the server cannot be reached. This may be a server issue, could be that it requires some "wake up time" after a period of inactivity due to its virtual machine. There may be many reasons for this. 

However, it is not a viewer issue. Btw, the message now disappears after 5 seconds...

**Comment by AliceBalfanz** [comment]
reopen when needed
