### ISSUE TITLE
xcube viewer takes a long time to load data 

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-viewer#61]
When opening http://viewer.cyanoalert.com/ it takes several minuites before one can access the cubes. The viewer first goes through all cubes configured in the server only after having gone though all of them the user can select a cube of interest. 

Maybe it would be better to only load the names of the available cubes and then whenever a user is interested in a cube, the cube is loaded?
Alternatively, the user can access the loaded cubes while the others are still loading in the background?

**Comment by forman** [comment]
This is because the CyanoAlert server associates massive amounts of vector data with each datasets. This ends up in an initial JSON response of around 60 MB.

The root cause is, that all dataset information is queried at once initially, therefore the solution is  implement lazy loading for dataset detail information namely place groups and coordinate values.
